# Generated by Django 3.2.19 on 2023-06-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_state', models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='closed', max_length=20)),
            ],
        ),
    ]
