# Generated by Django 3.2.19 on 2023-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_direction',
            field=models.CharField(choices=[('moving_up', 'MOVING_UP'), ('moving_down', 'MOVING_DOWN'), ('still', 'STILL')], default='still', max_length=32),
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_condtion',
            field=models.CharField(choices=[('working', 'WORKING'), ('not_working', 'NOT_WORKING'), ('in_maintenance', 'IN_MAINTENANCE')], default='working', max_length=32),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='door_state',
            field=models.CharField(choices=[('open', 'OPEN'), ('closed', 'CLOSED')], default='closed', max_length=32),
        ),
    ]
