# Generated by Django 3.2.19 on 2023-06-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0002_auto_20230627_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField()),
                ('destination_floor', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevators.elevator')),
            ],
        ),
    ]
